server:
  servlet:
    context-path: /api/v1
  port: 8096

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:aws://awseb-e-mym3zvhhhp-stack-awsebrdsdatabase-thk5l0e9akyp.ce14s8c4afrz.us-east-1.rds.amazonaws.com:3306/facturacion?createDatabaseIfNotExist=true
    username: root
    password: Mastermal2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
